// Step 2 (PORT_PROGRESS.md, glTF skinned-mesh import pipeline): exercises
// importGltfFromMemory()'s pure parsing logic, bgfx-free, against a hand-
// authored fixture (tests/fixtures/skinned_wheel_test.gltf -- a 4-vertex
// quad "wheel" fully weighted to a child joint of a root joint, generated by
// a one-off script, not a real art asset). No committed binary/.glb fixture
// exists anywhere else in this repo (tests/fixtures/trace_synthetic.txt is
// the closest precedent, a hand-authored plain-text fixture read via a
// repo-relative WORKING_DIRECTORY) -- this is the first, following that same
// "small hand-authored fixture, not a generated binary" convention, just in
// JSON glTF form instead of plain text.

#include "../src/render/mesh_import.h"

#include <cmath>
#include <cstdio>
#include <fstream>
#include <sstream>

namespace {
int g_failures = 0;

void expect(bool cond, const char* what) {
    if (!cond) {
        std::fprintf(stderr, "FAIL: %s\n", what);
        ++g_failures;
    }
}

void expectNear(const char* label, double got, double expected, double tol = 1e-5) {
    if (std::fabs(got - expected) > tol) {
        std::fprintf(stderr, "%s: got %.9g expected %.9g (diff %.3g)\n", label, got, expected, got - expected);
        ++g_failures;
    }
}
} // namespace

int main() {
    std::ifstream in("tests/fixtures/skinned_wheel_test.gltf", std::ios::binary);
    if (!in) {
        std::fprintf(stderr, "mesh_import_test: could not open tests/fixtures/skinned_wheel_test.gltf "
                             "(run from the repo root / build's WORKING_DIRECTORY)\n");
        return 1;
    }
    std::ostringstream ss;
    ss << in.rdbuf();
    const std::string json = ss.str();

    MeshImportResult result = importGltfFromMemory(json.data(), json.size());
    expect(result.ok, "importGltfFromMemory succeeds on the hand-authored fixture");
    if (!result.ok) {
        std::fprintf(stderr, "mesh_import_test: import error: %s\n", result.error.c_str());
        std::fprintf(stderr, "mesh_import_test: 1 FAILURES.\n");
        return 1;
    }
    const ImportedMesh& mesh = result.mesh;

    // ---- geometry ----
    expect(mesh.vertices.size() == 4, "4 vertices imported");
    expect(mesh.indices.size() == 6, "6 indices imported (2 triangles)");
    if (mesh.vertices.size() == 4) {
        expectNear("vertex 0 position.x", mesh.vertices[0].px, -0.5);
        expectNear("vertex 0 position.y", mesh.vertices[0].py, -0.5);
        expectNear("vertex 2 position.x", mesh.vertices[2].px, 0.5);
        expectNear("vertex 2 position.y", mesh.vertices[2].py, 0.5);
        expectNear("vertex 0 normal.z", mesh.vertices[0].nz, 1.0);
        expectNear("vertex 1 uv.u", mesh.vertices[1].u, 1.0);
        expectNear("vertex 2 uv.v", mesh.vertices[2].v, 1.0);
    }
    if (mesh.indices.size() == 6) {
        expect(mesh.indices[0] == 0 && mesh.indices[1] == 1 && mesh.indices[2] == 2, "first triangle is 0,1,2");
        expect(mesh.indices[3] == 0 && mesh.indices[4] == 2 && mesh.indices[5] == 3, "second triangle is 0,2,3");
    }

    // ---- skinning attributes: every vertex fully bound to joint 1 ----
    for (size_t i = 0; i < mesh.vertices.size(); ++i) {
        expect(mesh.vertices[i].joints[0] == 1, "vertex bound to joint index 1 (\"wheel\")");
        expectNear("vertex weight[0]", mesh.vertices[i].weights[0], 1.0);
        expectNear("vertex weight[1]", mesh.vertices[i].weights[1], 0.0);
    }

    // ---- material ----
    expectNear("baseColorFactor.r", mesh.baseColorFactor[0], 0.2);
    expectNear("baseColorFactor.g", mesh.baseColorFactor[1], 0.2);
    expectNear("baseColorFactor.a", mesh.baseColorFactor[3], 1.0);
    expect(mesh.baseColorImageBytes.empty(), "no embedded base color texture in this fixture");

    // ---- skin: 2 joints, "wheel" is a child of "root" ----
    expect(mesh.joints.size() == 2, "2 joints imported");
    if (mesh.joints.size() == 2) {
        expect(mesh.joints[0].name == "root", "joint 0 is \"root\"");
        expect(mesh.joints[0].parent == -1, "root joint has no parent");
        expect(mesh.joints[1].name == "wheel", "joint 1 is \"wheel\"");
        expect(mesh.joints[1].parent == 0, "wheel joint's parent is joint 0 (root)");

        // root's local bind matrix is identity (no translation/rotation/scale authored)
        expectNear("root local bind matrix is identity (translation.x)", mesh.joints[0].localBindMatrix[12], 0.0);
        // wheel's local bind matrix carries its authored +1 X translation
        expectNear("wheel local bind matrix translation.x", mesh.joints[1].localBindMatrix[12], 1.0);

        // inverse bind matrices round-trip exactly as authored (see the
        // fixture-generation script: root identity, wheel undoes -1 X)
        expectNear("root inverse bind matrix is identity (translation.x)", mesh.joints[0].inverseBindMatrix[12], 0.0);
        expectNear("wheel inverse bind matrix translation.x", mesh.joints[1].inverseBindMatrix[12], -1.0);
    }

    // ---- malformed input is rejected, not silently defaulted ----
    {
        const char bogus[] = "not a glTF file";
        MeshImportResult bad = importGltfFromMemory(bogus, sizeof(bogus));
        expect(!bad.ok, "malformed input reports failure rather than a partial/garbage result");
    }

    if (g_failures == 0) {
        std::printf("mesh_import_test: glTF skinned-mesh parsing all correct.\n");
        return 0;
    }
    std::fprintf(stderr, "mesh_import_test: %d FAILURES.\n", g_failures);
    return 1;
}
